<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE docmanager [
<!ELEMENT docmanager (docgroup+)>
<!ELEMENT docgroup (doc_group_id,groupname,documents)>
<!ELEMENT doc_group_id (#PCDATA)>
<!ELEMENT groupname (#PCDATA)>
<!ELEMENT documents (document*)>
<!ELEMENT document (url,docid,title,data,state,updatedate,createdate,description,language,creator)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT docid (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT data (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT updatedate (#PCDATA)>
<!ELEMENT createdate (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT language (#PCDATA)>
<!ELEMENT creator (#PCDATA)>
]>
<docmanager>
<docgroup>
<doc_group_id>196341</doc_group_id>
<groupname>Administrator</groupname>
<documents>
<document>
<url>https://sourceforge.net/docman/display_doc.php?docid=28108&amp;#x26;group_id=128058</url>
<docid>28108</docid>
<title>Clustered Hobbit Servers HOWTO</title>
<data>Install Clustered Hobbit Server

Caveats:
1. Example is done on 64-bit Redhat Fedora Core 3 systems.
2. The author loves to install everything in /opt
3. Network addresses and hostnames were changed to protect the innocent. You&amp;#x27;ll need to change these to match your network.
4. &amp;#x27;------------------------------------------------------------&amp;#x27; marks the begin and end of file content
5. This is a &amp;#x27;complete&amp;#x27; install including Apache, fping, etc.
6. This should work on other OS&amp;#x27;s, but the author hasn&amp;#x27;t personally tested it anywhere else. 
7. This configuration is Active/Passive with one backup waiting for the primary to fail
8. Read through the scripts carefully as items such as smtp setup and machine ip/names will need to change. 

Requirements: 

1. 2 similar boxes (this example uses Linux on Sun V20z&amp;#x27;s) setup with hostnames and network addresses (see Notes below).
2. At least one network interface. 2 is ideal so that you can have a dedicated crossover cable heartbeat between the systems. 
3. Enough time and patience to get through the doc, let alone the install. 


Notes:
1. 192.168.1.1 is the default route for the network
2. 192.168.1.146 and 192.168.1.148 are the ip addresses of host1.yourdomain.com and host2.yourdomain.com respectively
3. 192.168.1.150 is the clustered address with the DNS of monitor.yourdomain.com.  This address should be in the bb-hosts file with the following entries. All bb clients will send to this host as the primary. Note that the 2 individual hosts are considered &amp;#x27;normal&amp;#x27; monitored hosts, while the clustered identity is the BBDISPLAY/BBPAGER/BBNET, etc.


192.168.1.150   monitor.yourdomain.com      # BBDISPLAY BBPAGER BBNET bbd http://monitor.yourdomain.com/
192.168.1.146   host1.yourdomain.com	    #
192.168.1.148   host2.yourdomain.com

4. Users include:
- monitor with group monitor : this user runs hobbit and the web server
- hacluster with group haclient : this user runs the cluster daemons, etc. 

5. This document is subject to change as the install is still being thoroughly tested. 


HEARTBEAT 
***************************

BUILD: 

heartbeat-1.2.3

&amp;#x26;gt; ./configure --prefix=/opt/heartbeat-1.2.3 --with-initdir=/etc/init.d --with-group-name=haclient --with-group-id=502 --with-ccmuser-name=hacluster --with-ccuser-id=502 --with-pic
&amp;#x26;gt; make
&amp;#x26;gt; make install

* These changes need to be made in order for everything to work properly

Heartbeat permissions

&amp;#x26;gt; chmod o+rx /opt/heartbeat
&amp;#x26;gt; chmod o+rx /opt/heartbeat/lib
&amp;#x26;gt; chmod u+s /opt/heartbeatbeat/lib/heartbeat/ipfail
&amp;#x26;gt; chmod u+s /opt/heartbeatbeat/lib/heartbeat/ccm
&amp;#x26;gt; chmod u+s /opt/heartbeatbeat/lib/heartbeat/ccm_testclient

CCM Setup
&amp;#x26;gt; mkdir -p /var/lib/heartbeat/ccm

CONFIG FILES: 

/opt/heartbeat/etc/ha.d/authkeys (IDENTICAL ON BOTH SERVERS)
------------------------------------------------------------
auth 1
1 sha1 &amp;#x26;quot;[your password]&amp;#x26;quot;
2 md5 &amp;#x26;quot;[your password]&amp;#x26;quot;
3 crc
------------------------------------------------------------

/opt/heartbeat/etc/ha.d/haresources (IDENTICAL)
------------------------------------------------------------
#
# Monitoring Resources Configuration File
#

# Hobbit/Scripting resource
host1.yourdomain.com IPaddr::192.168.1.150/8/eth0 hobbit mirror mon MailTo::youremail@yourdomain.com::HobbitFailOver


------------------------------------------------------------

/opt/heartbeat/etc/ha.d/ha.cf (PRIMARY SERVER):
------------------------------------------------------------
# HA Config File: monitoring infrastructure
#

# Logging
debugfile /var/log/ha-debug
debug 1

logfile /var/log/ha-log

# Global HA Configuration
keepalive 2
deadtime 30
warntime 30

initdead 120

udpport 694

# Interfaces for broadcast heartbeats
bcast   eth2

# Multicast heartbeats
# mcast eth0 225.0.0.1 694 1 0

# Unicast heartbeats
ucast eth0 192.168.1.148
ucast eth2 172.16.0.2

# Failback automatically
auto_failback on

# Nodes
node    host1.yourdomain.com
node    host2.yourdomain.com

# Processes started and stopped with heartbeat
respawn hacluster /opt/heartbeat/lib/heartbeat/ipfail
respawn hacluster /opt/heartbeat/lib/heartbeat/ccm -d

# ipfail configuration
ping 192.168.1.1

deadping 30

apiauth ipfail uid=hacluster,root
apiauth ccm uid=hacluster,root
apiauth ping gid=haclient uid=blynch,root
apiauth default gid=haclient

# coredumps true
# coreroot /tmp/cores
------------------------------------------------------------

/opt/heartbeat/etc/ha.d/ha.cf (SECONDARY SERVER):
------------------------------------------------------------
# HA Config File: monitoring infrastructure
#

# Logging
debugfile /var/log/ha-debug
debug 1

logfile /var/log/ha-log

# Global HA Configuration
keepalive 2
deadtime 30
warntime 30

initdead 120

udpport 694

# Interfaces for broadcast heartbeats
bcast   eth2

# Multicast heartbeats
# mcast eth0 225.0.0.1 694 1 0

# Unicast heartbeats
ucast eth0 192.168.1.146
ucast eth2 172.16.0.1

# Failback automatically
auto_failback on

# Nodes
node    host1.yourdomain.com
node    host2.yourdomain.com

# Processes started and stopped with heartbeat
respawn hacluster /opt/heartbeat/lib/heartbeat/ipfail
respawn hacluster /opt/heartbeat/lib/heartbeat/ccm -d

# ipfail configuration
ping 192.168.1.1 

deadping 30

apiauth ipfail uid=hacluster,root
apiauth ccm uid=hacluster,root
apiauth ping gid=haclient uid=blynch,root
apiauth default gid=haclient

# coredumps true
# coreroot /tmp/cores
------------------------------------------------------------

STARTUP:

&amp;#x26;gt; chkconfig --add heartbeat
&amp;#x26;gt; chkconfig --level 345 heartbeat on


HOBBIT RESOURCE SCRIPT (different from the normal hobbit start script)
NOTES:  Do not add hobbit to the normal system startup.  It will be handled by the cluster software. 

/opt/heartbeat/etc/ha.d/resource.d/hobbit:
------------------------------------------------------------

#!/bin/sh
#
# Hobbit
#
# Description:  Manages a Hobbit Server as a High-Availability
#               resource
#
#
# Author:       Brian Lynch
#
# An example usage in /etc/ha.d/haresources:
#       node1  10.0.0.170 hobbit
#
# See usage() function below for more details...
#
unset LC_ALL; export LC_ALL
unset LANGUAGE; export LANGUAGE

usage() {
  methods=`hobbit_methods | grep -v methods`
  methods=`echo $methods | tr &amp;#x27; &amp;#x27; &amp;#x27;|&amp;#x27;`
  cat &amp;#x26;lt;&amp;#x26;lt;-! &amp;#x26;gt;&amp;#x26;amp;1
        usage: $0 methods

        $0 manages a Hobbit Server instance as an HA resource.

        The &amp;#x27;start&amp;#x27; operation starts the database.
        The &amp;#x27;stop&amp;#x27; operation stops the database.
        The &amp;#x27;status&amp;#x27; operation reports whether the database is running
        The &amp;#x27;monitor&amp;#x27; operation reports whether the database seems to be working
        The &amp;#x27;methods&amp;#x27; operation reports on the methods $0 supports

        !
  exit 1

}


prefix=/opt/heartbeat-1.2.3
exec_prefix=/opt/heartbeat-1.2.3
. /opt/heartbeat-1.2.3/etc/ha.d/shellfuncs
# . /etc/ha.d/shellfuncs
SH=/bin/bash


#
# methods: What methods/operations do we support?
#
hobbit_methods() {
  cat &amp;#x26;lt;&amp;#x26;lt;-!
        start
        stop
        status
        monitor
        methods
        !
}


#
#       Run the given command in the hobbit monitor environment...
#
runasmonitor() {
        su monitor -c &amp;#x26;quot;cd /opt/hobbit/server;  $*&amp;#x26;quot;
}

#
#       Run a command as the Hobbit User &amp;#x26;quot;monitor&amp;#x26;quot;, and log the output
#
logasmonitor() {
        output=`runasmonitor $*`
        rc=$?
        if
          [ $rc -eq 0 ]
        then
          ha_log &amp;#x26;quot;info: $output&amp;#x26;quot;
        else
          ha_log &amp;#x26;quot;ERROR: $output&amp;#x26;quot;
        fi
        return $rc
}

#
# hobbit_start: Start the hobbit server
#
hobbit_start() {
  if
    output=`runasmonitor ./hobbit.sh start`
  then
    : Hurray! Hobbit started OK
    ha_log &amp;#x26;quot;info: Hobbit Server started: $output&amp;#x26;quot;
  else
    case $output in
      &amp;#x26;quot;Hobbit appears to be running&amp;#x26;quot;*)
                ha_log &amp;#x26;quot;info: Hobbit Server is already running: $output&amp;#x26;quot;;;

      *)        ha_log &amp;#x26;quot;ERROR: $output&amp;#x26;quot;; return 1;;
    esac
  fi
  rc=`hobbit_status`
  return $rc;
}

#
# hobbit_stop: Stop the hobbit server
#
hobbit_stop() {
  # We ignore the instance, the info we need is already in $vars
  rc=0
  if
    output=`runasmonitor ./hobbit.sh stop`
  then
    : Hobbit stopped OK
    ha_log &amp;#x26;quot;info: Hobbit Server stopped: $output&amp;#x26;quot;
  else
    case $output in

      &amp;#x26;quot;Hobbit is not running&amp;#x26;quot;*)
                ha_log &amp;#x26;quot;info: $output&amp;#x26;quot;;;

      *)        ha_log &amp;#x26;quot;ERROR: Hobbit Server stop failed: $output&amp;#x26;quot;
                rc=1;;
    esac
  fi
  return $rc
}


#
# hobbit_status: is the hobbit server running?
#
hobbit_status() {
  # We ignore the instance, the info we need is already in $vars
  pscount=`runasmonitor ./hobbit.sh status | grep &amp;#x27;running with PID&amp;#x27; | wc -l`
  netstat=`netstat -an | grep LISTEN | grep 1984 | wc -l`
  test $pscount -eq 1 -a $netstat -eq 1
}

#
# hobbit_monitor: Can the given db2 instance do anything useful?
#
hobbit_monitor() {

  CMD=&amp;#x26;quot;bin/bb monitor &amp;#x27;query monitor,yourdomain,com.hobbitd&amp;#x27;; rc=\$?; exit \$rc&amp;#x26;quot;

  : Running this command: $CMD

  if
    output=`runasmonitor $CMD`
  then
    : Command succeeded!
  else
    ha_log &amp;#x26;quot;Error: Hobbit Server not available: output&amp;#x26;quot;
    return 1
  fi
  : ha_log &amp;#x26;quot;info: Hobbit Server appears to be running&amp;#x26;quot;
}

#
#       &amp;#x27;main&amp;#x27; starts here...
#

if
  [ $# -le 0 ]
then
  if
    [ &amp;#x26;quot;methods&amp;#x26;quot; = &amp;#x26;quot;$1&amp;#x26;quot; ]
  then
    hobbit_methods
    exit $?
  else
    usage
    exit $?
  fi
fi

US=`id -u -n`
US=`echo $US`
if
  [ $US != root -a $US != $1 ]
then
  ha_log &amp;#x26;quot;ERROR: $0 must be run as root or $1&amp;#x26;quot;
  exit 1
fi

# What kind of method was invoked?
case &amp;#x26;quot;$1&amp;#x26;quot; in

  start)        hobbit_start
                exit $?;;

  stop)         hobbit_stop
                exit $?;;

  status)       if
                  hobbit_status
                then
                  echo Hobbit Server is running
                  exit 0
                else
                  echo Hobbit Server is stopped
                  exit 1
                fi
                exit $?;;

  monitor)      hobbit_monitor
                exit $?;;

  methods)      hobbit_methods
                exit $?;;
esac

usage
------------------------------------------------------------


RSYNC SETUP

Follow the rsync.txt instructions in /opt/heartbeat/share/docs/heartbeat-1.2.3.

Make the script directory
&amp;#x26;gt; mkdir -p /opt/sysadmin/scripts/sync

Create the following scripts. 

/opt/sysadmin/scripts/sync/EnvConfig.pm (Sets up the environment):
------------------------------------------------------------
# Configuration file for all scripts, including host definitions, etc.

package EnvConfig;

#www_host = &amp;#x26;quot;wwwdev.domain.com&amp;#x26;quot;;
$www_host = &amp;#x26;quot;wwwint.domain.com&amp;#x26;quot;;
#www_host = &amp;#x26;quot;wwwprod.domain.com&amp;#x26;quot;;

$sshpath = &amp;#x26;quot;/usr/bin/ssh&amp;#x26;quot;;

$rsyncoptions = &amp;#x26;quot;-aurlq --delete&amp;#x26;quot;;
#$rsyncoptions = &amp;#x26;quot;-aurlv&amp;#x26;quot;;

$smtphost = &amp;#x27;mailhost&amp;#x27;;

$Debug = 0;
1;
------------------------------------------------------------

/opt/sysadmin/scripts/sync/whohostlib.pm (Functions to figure out if the scripts are running on the cluster master):
------------------------------------------------------------
#!/usr/bin/perl

use strict;
use diagnostics;

package whohostlib;
sub whohost {
    my $other;
    my $me;

    my $x = `grep node /opt/heartbeat/etc/ha.d/ha.cf | sed -e &amp;#x26;quot;s/node//g&amp;#x26;quot;`;
    my @p = split(&amp;#x27; &amp;#x27;, $x);
    $me = `hostname -s`;
    chomp $me;

    my @node1_array = split(&amp;#x27;\.&amp;#x27;, $p[0]);
    my @node2_array = split(&amp;#x27;\.&amp;#x27;, $p[1]);

    my $node1 = $node1_array[0];
    my $node2 = $node2_array[0];

    if($me eq $node1) {
        $other = $node2;
    } else {
        $other = $node1;
    }

    return($me,$other);
}

#By doing &amp;#x26;quot;grep mirror haresources&amp;#x26;quot;, we peel off the line with the info we want...the cluster IP.  Mirror will be added to you haresources later...
sub whostatus {
    my $status = 0;
    my $x = `grep mirror /opt/heartbeat/etc/ha.d/haresources`;
    my @p = split(&amp;#x27; &amp;#x27;,$x);
    my $ip = $p[1];
    $ip =~ s/IPaddr:://g;
    $x = `/opt/heartbeat/etc/ha.d/resource.d/IPaddr $ip status`;

    # If I am primary, return 1 else return 0
    if ($x =~ /running/) {
       $status = 1;
    } else {
       $status = 0;
    }

    return $status;
}

1; #Return True Value
------------------------------------------------------------

/opt/sysadmin/scripts/sync/kill_synchs.sh (kills sync during a shutdown):
------------------------------------------------------------
#!/bin/sh
ps ax | grep synch | awk {&amp;#x27;print $1&amp;#x27;} | xargs -n1 kill -9

/opt/sysadmin/scripts/sync/long_synch_all
#!/usr/bin/perl

use strict;
use diagnostics;

use lib &amp;#x26;quot;/opt/sysadmin/scripts/sync&amp;#x26;quot;;
use whohostlib;
use EnvConfig;
use Mail::Sendmail;

#Take care of two-way syncing case during shutdown of one server.  Skips the first try to sync after failover.
if ( -e &amp;#x26;quot;/var/lock/subsys/mirrorstop&amp;#x26;quot; ) {
    unlink &amp;#x26;quot;/var/lock/subsys/mirrorstop&amp;#x26;quot;;
    exit;
}

# Only sync if serving IP
my $dirname = &amp;#x26;quot;&amp;#x26;quot;;
my $filename = &amp;#x26;quot;&amp;#x26;quot;;

#Get server that this is running on...
my $me = &amp;#x26;quot;&amp;#x26;quot;;
my $other = &amp;#x26;quot;&amp;#x26;quot;;
($me,$other) = whohostlib::whohost;

if (&amp;#x26;amp;whohostlib::whostatus() == 1)
{
    #I&amp;#x27;m serving!  You want fries with that?

    #Only sync if other node is running heartbeat:
    my $tst = `$EnvConfig::sshpath local-$other /etc/rc.d/init.d/heartbeat status`;
    # For 0.4.9.2 and earlier use  ---&amp;#x26;gt;    if ($tst =~ /running.../) {
    # For 0.4.9 &amp;#x26;quot;beta&amp;#x26;quot; versions...
    if ($tst =~ /heartbeat OK/) {
        #make sure previous mirror has completed...

        #To avoid hard link probs over partitions, created /var/lock/subsys/.DONOTREMOVE file
        if (link(&amp;#x26;quot;/var/lock/subsys/.DONOTREMOVE&amp;#x26;quot;, &amp;#x26;quot;/var/lock/subsys/mirror&amp;#x26;quot;)) {

        print &amp;#x26;quot;running rsync\n&amp;#x26;quot;;
            # /opt/hobbit/data/ - Data for Hobbit
                my @dirlist = ( &amp;#x26;quot;/opt/hobbit/data/&amp;#x26;quot; );
                foreach $dirname (@dirlist) {
                    system &amp;#x26;quot;/usr/bin/rsync --rsh=$EnvConfig::sshpath $EnvConfig::rsyncoptions $dirname local-$other:$dirname&amp;#x26;quot;;
            }

            # /opt/hobbit/server/tmp/hobbitd_alert.chk - Checkpoing file for Hobbit Alert Daemon
                my @filelist = ( );
                foreach $filename (@filelist) {
                    system &amp;#x26;quot;/usr/bin/rsync --rsh=$EnvConfig::sshpath $EnvConfig::rsyncoptions $filename local-$other:$filename&amp;#x26;quot;;
                }

            # release rsync process
            unlink &amp;#x26;quot;/var/lock/subsys/mirror&amp;#x26;quot;;
        } else {
        print &amp;#x26;quot;next process running before last one completed\n&amp;#x26;quot;;
            my $ddd = `date`;
            my $subject = &amp;#x26;quot;Next RSYNC process starting before previous has completed!\n&amp;#x26;quot;;
            my $message = $subject.$ddd;

            sendmail (&amp;#x27;smtp&amp;#x27; =&amp;#x26;gt; $EnvConfig::smtphost,
                &amp;#x27;To&amp;#x27; =&amp;#x26;gt; &amp;#x27;admin@domain.com,admin2@domain.com&amp;#x27;,
                &amp;#x27;From&amp;#x27; =&amp;#x26;gt; &amp;#x27;cluster@domain.com&amp;#x27;,
                &amp;#x27;Reply-To&amp;#x27; =&amp;#x26;gt; &amp;#x27;cluster@domain.com&amp;#x27;,
                &amp;#x27;Subject&amp;#x27; =&amp;#x26;gt; $subject,
                &amp;#x27;Message&amp;#x27; =&amp;#x26;gt; $message)
            or warn &amp;#x26;quot;Next RSYNC process starting before previous has completed (Couldn&amp;#x27;t send email)&amp;#x26;quot;;

            #Try to get to known state by killing all synch procs and removing link...
            unlink &amp;#x26;quot;/var/lock/subsys/mirror&amp;#x26;quot;;
            exec &amp;#x26;quot;/opt/sysadmin/scripts/sync/kill_synchs.sh&amp;#x26;quot;;
            #&amp;#x26;quot;kill_synchs.sh is a one liner:  ps ax | grep synch_all | awk {&amp;#x27;print $1&amp;#x27;} | xargs -n1 kill -9
            exit;
        }
    }
}
------------------------------------------------------------

/opt/sysadmin/script/sync/pagescript.pl (Used to page the admin in the event of a problem): 
------------------------------------------------------------
#!/usr/bin/perl

use lib &amp;#x26;quot;/opt/sysadmin/script/sync&amp;#x26;quot;;
use EnvConfig;
use Mail::Sendmail;

# See how we are called
if($#ARGV == 1)
{
  $mailto = $ARGV[0];
  $subject = $ARGV[1];
}
else
{
  print &amp;#x26;quot;Usage: pagescript.pl [email] [subject]\n&amp;#x26;quot;;
  exit -1;
}

my $ddd = `date`;
my $message = $subject.&amp;#x26;quot; &amp;#x26;quot;.$ddd;

print &amp;#x26;quot;Mailto: $mailto\n&amp;#x26;quot;;
print &amp;#x26;quot;Subject: $message\n&amp;#x26;quot;;

# Send mail to the administrator
sendmail (&amp;#x27;smtp&amp;#x27; =&amp;#x26;gt; $EnvConfig::smtphost,
    &amp;#x27;To&amp;#x27; =&amp;#x26;gt; &amp;#x27;$mailto&amp;#x27;,
    &amp;#x27;From&amp;#x27; =&amp;#x26;gt; &amp;#x27;monitor@yourdomain.com&amp;#x27;,
    &amp;#x27;Reply-To&amp;#x27; =&amp;#x26;gt; &amp;#x27;monitor@yourdomain.com&amp;#x27;,
    &amp;#x27;Subject&amp;#x27; =&amp;#x26;gt; $subject,
    &amp;#x27;Message&amp;#x27; =&amp;#x26;gt; $message);

# Log to the HA Log
open(LOG,&amp;#x26;quot;&amp;#x26;gt;&amp;#x26;gt;/var/log/ha-log&amp;#x26;quot;);
print LOG &amp;#x26;quot;$message\n&amp;#x26;quot;;
close LOG;
------------------------------------------------------------



/opt/sysadmin/scripts/sync/synch_all.pl (main synch script ; to be run every 10 minutes):
------------------------------------------------------------
#!/usr/bin/perl

use strict;
use diagnostics;

use lib &amp;#x26;quot;/opt/sysadmin/scripts/sync&amp;#x26;quot;;
use whohostlib;
use EnvConfig;
use Mail::Sendmail;

#Take care of two-way syncing case during shutdown of one server.  Skips the first try to sync after failover.
if ( -e &amp;#x26;quot;/var/lock/subsys/mirrorstop&amp;#x26;quot; ) {
    unlink &amp;#x26;quot;/var/lock/subsys/mirrorstop&amp;#x26;quot;;
    exit;
}

# Only sync if serving IP
my $dirname = &amp;#x26;quot;&amp;#x26;quot;;
my $filename = &amp;#x26;quot;&amp;#x26;quot;;

#Get server that this is running on...
my $me = &amp;#x26;quot;&amp;#x26;quot;;
my $other = &amp;#x26;quot;&amp;#x26;quot;;
($me,$other) = whohostlib::whohost;

if (&amp;#x26;amp;whohostlib::whostatus() == 1)
{
    #I&amp;#x27;m serving!  You want fries with that?

    #Only sync if other node is running heartbeat:
    my $tst = `$EnvConfig::sshpath local-$other /etc/rc.d/init.d/heartbeat status`;
    # For 0.4.9.2 and earlier use  ---&amp;#x26;gt;    if ($tst =~ /running.../) {
    # For 0.4.9 &amp;#x26;quot;beta&amp;#x26;quot; versions...
    if ($tst =~ /heartbeat OK/) {
        #make sure previous mirror has completed...

        #To avoid hard link probs over partitions, created /var/lock/subsys/.DONOTREMOVE file
        if (link(&amp;#x26;quot;/var/lock/subsys/.DONOTREMOVE&amp;#x26;quot;, &amp;#x26;quot;/var/lock/subsys/mirror&amp;#x26;quot;)) {

        print &amp;#x26;quot;running rsync\n&amp;#x26;quot;;
            # /opt/hobbit/server/etc/ - Configuration for Hobbit
            # /opt/hobbit/server/www/ - Build Web Pages for Hobbit
            # /opt/hobbit/server/web/ - Header Files for Hobbit
            # /opt/hobbit/server/ext/ - Executable Files for Hobbit
            # /opt/sysadmin/scripts/sync/ - Synchronization Scripts
                my @dirlist = ( &amp;#x26;quot;/opt/hobbit/server/etc/&amp;#x26;quot;, &amp;#x26;quot;/opt/hobbit/server/www/&amp;#x26;quot;, &amp;#x26;quot;/opt/hobbit/server/web/&amp;#x26;quot;, &amp;#x26;quot;/opt/hobbit/server/ext/&amp;#x26;quot;, &amp;#x26;quot;/opt/sysadmin/scripts/sync/&amp;#x26;quot;);
                foreach $dirname (@dirlist) {
                    system &amp;#x26;quot;/usr/bin/rsync --rsh=$EnvConfig::sshpath $EnvConfig::rsyncoptions $dirname local-$other:$dirname&amp;#x26;quot;;
            }

            # /opt/hobbit/server/tmp/hobbitd.chk - Checkpoint file for Hobbit Daemon
            # /opt/hobbit/server/tmp/hobbitd_alert.chk - Checkpoing file for Hobbit Alert Daemon
                my @filelist = ( &amp;#x26;quot;/opt/hobbit/server/tmp/hobbitd.chk&amp;#x26;quot;, &amp;#x26;quot;/opt/hobbit/server/tmp/hobbitd_alert.chk&amp;#x26;quot; );
                foreach $filename (@filelist) {
                    system &amp;#x26;quot;/usr/bin/rsync --rsh=$EnvConfig::sshpath $EnvConfig::rsyncoptions $filename local-$other:$filename&amp;#x26;quot;;
                }

            # release rsync process
            unlink &amp;#x26;quot;/var/lock/subsys/mirror&amp;#x26;quot;;
        } else {
        print &amp;#x26;quot;next process running before last one completed\n&amp;#x26;quot;;
            my $ddd = `date`;
            my $subject = &amp;#x26;quot;Next RSYNC process starting before previous has completed!\n&amp;#x26;quot;;
            my $message = $subject.$ddd;

            sendmail (&amp;#x27;smtp&amp;#x27; =&amp;#x26;gt; $EnvConfig::smtphost,
                &amp;#x27;To&amp;#x27; =&amp;#x26;gt; &amp;#x27;unixadmins@yourdomain.com&amp;#x27;,
                &amp;#x27;From&amp;#x27; =&amp;#x26;gt; &amp;#x27;cluster@monitor.yourdomain.com&amp;#x27;,
                &amp;#x27;Reply-To&amp;#x27; =&amp;#x26;gt; &amp;#x27;cluster@monitor.yourdomain.com&amp;#x27;,
                &amp;#x27;Subject&amp;#x27; =&amp;#x26;gt; $subject,
                &amp;#x27;Message&amp;#x27; =&amp;#x26;gt; $message)
            or warn &amp;#x26;quot;Next RSYNC process starting before previous has completed (Couldn&amp;#x27;t send email)&amp;#x26;quot;;

            #Try to get to known state by killing all synch procs and removing link...
            unlink &amp;#x26;quot;/var/lock/subsys/mirror&amp;#x26;quot;;
            exec &amp;#x26;quot;/opt/sysadmin/scripts/sync/kill_synchs.sh&amp;#x26;quot;;
            #&amp;#x26;quot;kill_synchs.sh is a one liner:  ps ax | grep synch_all | awk {&amp;#x27;print $1&amp;#x27;} | xargs -n1 kill -9
            exit;
        }
    }
}
------------------------------------------------------------

/opt/sysadmin/scripts/sync/long_synch_all.pl (used to sync bigger directories; run every night): 
------------------------------------------------------------
#!/usr/bin/perl

use strict;
use diagnostics;

use lib &amp;#x26;quot;/opt/sysadmin/scripts/sync&amp;#x26;quot;;
use whohostlib;
use EnvConfig;
use Mail::Sendmail;

#Take care of two-way syncing case during shutdown of one server.  Skips the first try to sync after failover.
if ( -e &amp;#x26;quot;/var/lock/subsys/mirrorstop&amp;#x26;quot; ) {
    unlink &amp;#x26;quot;/var/lock/subsys/mirrorstop&amp;#x26;quot;;
    exit;
}

# Only sync if serving IP
my $dirname = &amp;#x26;quot;&amp;#x26;quot;;
my $filename = &amp;#x26;quot;&amp;#x26;quot;;

#Get server that this is running on...
my $me = &amp;#x26;quot;&amp;#x26;quot;;
my $other = &amp;#x26;quot;&amp;#x26;quot;;
($me,$other) = whohostlib::whohost;

if (&amp;#x26;amp;whohostlib::whostatus() == 1)
{
    #I&amp;#x27;m serving!  You want fries with that?

    #Only sync if other node is running heartbeat:
    my $tst = `$EnvConfig::sshpath local-$other /etc/rc.d/init.d/heartbeat status`;
    # For 0.4.9.2 and earlier use  ---&amp;#x26;gt;    if ($tst =~ /running.../) {
    # For 0.4.9 &amp;#x26;quot;beta&amp;#x26;quot; versions...
    if ($tst =~ /heartbeat OK/) {
        #make sure previous mirror has completed...

        #To avoid hard link probs over partitions, created /var/lock/subsys/.DONOTREMOVE file
        if (link(&amp;#x26;quot;/var/lock/subsys/.DONOTREMOVE&amp;#x26;quot;, &amp;#x26;quot;/var/lock/subsys/mirror&amp;#x26;quot;)) {

        print &amp;#x26;quot;running rsync\n&amp;#x26;quot;;
            # /opt/hobbit/data/ - Data for Hobbit
                my @dirlist = ( &amp;#x26;quot;/opt/hobbit/data/&amp;#x26;quot; );
                foreach $dirname (@dirlist) {
                    system &amp;#x26;quot;/usr/bin/rsync --rsh=$EnvConfig::sshpath $EnvConfig::rsyncoptions $dirname local-$other:$dirname&amp;#x26;quot;;
            }

                my @filelist = ( );
                foreach $filename (@filelist) {
                    system &amp;#x26;quot;/usr/bin/rsync --rsh=$EnvConfig::sshpath $EnvConfig::rsyncoptions $filename local-$other:$filename&amp;#x26;quot;;
                }

            # release rsync process
            unlink &amp;#x26;quot;/var/lock/subsys/mirror&amp;#x26;quot;;
        } else {
        print &amp;#x26;quot;next process running before last one completed\n&amp;#x26;quot;;
            my $ddd = `date`;
            my $subject = &amp;#x26;quot;Next RSYNC process starting before previous has completed!\n&amp;#x26;quot;;
            my $message = $subject.$ddd;

            sendmail (&amp;#x27;smtp&amp;#x27; =&amp;#x26;gt; $EnvConfig::smtphost,
                &amp;#x27;To&amp;#x27; =&amp;#x26;gt; &amp;#x27;admin@domain.com,admin2@domain.com&amp;#x27;,
                &amp;#x27;From&amp;#x27; =&amp;#x26;gt; &amp;#x27;cluster@domain.com&amp;#x27;,
                &amp;#x27;Reply-To&amp;#x27; =&amp;#x26;gt; &amp;#x27;cluster@domain.com&amp;#x27;,
                &amp;#x27;Subject&amp;#x27; =&amp;#x26;gt; $subject,
                &amp;#x27;Message&amp;#x27; =&amp;#x26;gt; $message)
            or warn &amp;#x26;quot;Next RSYNC process starting before previous has completed (Couldn&amp;#x27;t send email)&amp;#x26;quot;;

            #Try to get to known state by killing all synch procs and removing link...
            unlink &amp;#x26;quot;/var/lock/subsys/mirror&amp;#x26;quot;;
            exec &amp;#x26;quot;/opt/sysadmin/scripts/sync/kill_synchs.sh&amp;#x26;quot;;
            #&amp;#x26;quot;kill_synchs.sh is a one liner:  ps ax | grep synch_all | awk {&amp;#x27;print $1&amp;#x27;} | xargs -n1 kill -9
            exit;
        }
    }
}
------------------------------------------------------------

CRONTAB ENTRIES (setup on both hosts; the script finds the cluster master and only runs there):

# Frequent RSYNC mirror : Tied to the hobbit resource
10,20,30,40,50 * * * * /opt/sysadmin/scripts/sync/synch_all.pl

# Long-running RSYNC mirror : Used for &amp;#x26;quot;large&amp;#x26;quot; files and done nightly
0 8 * * * /opt/sysadmin/scripts/sync/long_synch_all.pl


INTEGRATION INTO HEARTBEAT

1. Add the &amp;#x27;mirror&amp;#x27; script to the resource.d directory.

/opt/heartbeat/etc/ha.d/resource.d/mirror:
------------------------------------------------------------

#!/usr/bin/perl

use lib &amp;#x26;quot;/opt/sysadmin/scripts/sync&amp;#x26;quot;;
use whohostlib;

# See how we were called.
if ($#ARGV == 0) {
    $switch = $ARGV[0];
} else {
    print &amp;#x26;quot;Usage: mirror {start|stop|status|restart}\n&amp;#x26;quot;;
    exit -1;
}

#  start)

if ($switch eq &amp;#x26;quot;start&amp;#x26;quot;) {
    #Make sure to skip first sync.....
    ($me,$other) = whohostlib::whohost;
    system (&amp;#x26;quot;/usr/bin/ssh local$me /bin/touch /var/lock/subsys/mirrorstop&amp;#x26;quot;);
    #Notify admins of startup....
    open (XXX,&amp;#x26;quot;/opt/sysadmin/scripts/sync/.pagelist&amp;#x26;quot;);
    $hh = `hostname`;
    chomp $hh;
    while (&amp;#x26;lt;XXX&amp;#x26;gt;) {
    chomp;
    system &amp;#x26;quot;/opt/sysadmin/scripts/sync/pagescript.pl $_ \&amp;#x26;quot;Starting up heartbeat services on node $hh\&amp;#x26;quot;&amp;#x26;quot;;
    }
    close XXX;

} elsif ($switch eq &amp;#x26;quot;stop&amp;#x26;quot;) {
    #stop)

    print &amp;#x26;quot;Mirror stop: \n&amp;#x26;quot;;

    #Am I serving???
    #We&amp;#x27;ll consider mirror to be &amp;#x26;quot;running&amp;#x26;quot; if the IP is on this box...
    $x = `grep mirror /opt/heartbeat/etc/ha.d/haresources`;